SYMBOLS = [
    # "DIGIUSDT"
    # "BTC/USDT",
    # "ETH/USDT",
    # "SOL/USDT",
]

DEVIATION_PERIOD_MINUTES =  15
TRESHOLD_DEVIATION_PROCENTAGE = 25 #Procentage
UPPER_PERSENTAGE = 2 # Procentage
LOWER_PERSENTAGE = 2 # Procentage

TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""

